### ISSUE TITLE
Test parsed_grid_generator 10, 11, 12 failing

### ISSUE THREAD

**Issue by mraveri** [mathLab/deal2lkit#296]
After successfully building the library and the test with the latest deal.ii master the test of parsed grid generator fail. Here's the failing diff (all the same):

```
----------------
##2       #:5   <== 11
##2       #:5   ==> 10
@ Absolute error = 1.0000000000e+0, Relative error = 1.0000000000e-1
----------------
##9       #:5   <== 11
##9       #:5   ==> 10
@ Absolute error = 1.0000000000e+0, Relative error = 1.0000000000e-1

+++  File             "/home/parallels/Desktop/deal2lkit/tests/parsed_grid_generator/parsed_grid_generator_12.output" differs from file "output"
```

**Comment by luca-heltai** [comment]
I think this has been fixed.

**Comment by asartori86** [comment]
I still get this three tests failing for a diff like the following

```
----------------
##2       #:5   <== 11
##2       #:5   ==> 14
@ Absolute error = 3.0000000000e+0, Relative error = 2.7272727273e-1
----------------
##5       #:134 <== 17
##5       #:134 ==> 0
@ Absolute error = 1.7000000000e+1, Relative error = Inf
##5       #:135 <== 1
##5       #:135 ==> 0
@ Absolute error = 1.0000000000e+0, Relative error = Inf
##5       #:136 <== 0
##5       #:136 ==> 18
@ Absolute error = 1.8000000000e+1, Relative error = Inf
##5             <==
##5       #>137 ==> 1 0
@ Line 5 in file "/home/alberto/opt/src/deal2lkit/tests/parsed_grid_generator/parsed_grid_generator_11.output" is shorter than expected!
```

@luca-heltai, what should we do with these tests?
